import { evaluate, type EmployeeState, type TraceNode } from './predicate';
import type {
  ConsideredRule,
  Effect,
  EmployeeResolution,
  ResolvedAssignment,
  Rule,
  Slot,
  SlotResolution,
} from './types';

interface Candidate {
  rule: Rule;
  matched: boolean;
  trace: TraceNode;
}

/**
 * Total ordering for rule tie-break (DECISIONS.md D9):
 * manual DESC, priority DESC, rule_created_at ASC, rule_id ASC.
 *
 * Manual comes FIRST, before priority. An ordering position is an invariant; a
 * priority ceiling is a convention every write path would have to maintain, and
 * the API default (priority 0) already broke it once. No priority value can now
 * break manual precedence. `priority` still orders manual rules against each
 * other and automatic rules against each other — that is what it is for.
 *
 * Every term must be stable across versions of the same rule. created_at and
 * the per-version surrogate id are regenerated by the write path, so they are
 * disqualified from this comparator.
 */
export function compareRules(a: Rule, b: Rule): number {
  if (a.source !== b.source) {
    return a.source === 'manual' ? -1 : 1;
  }
  if (a.priority !== b.priority) {
    return b.priority - a.priority;
  }
  const aTime = a.ruleCreatedAt.getTime();
  const bTime = b.ruleCreatedAt.getTime();
  if (aTime !== bTime) {
    return aTime - bTime;
  }
  if (a.ruleId !== b.ruleId) return a.ruleId.localeCompare(b.ruleId);
  if (a.targetId !== b.targetId) return a.targetId.localeCompare(b.targetId);
  return a.name.localeCompare(b.name);
}

function appliesToEmployee(rule: Rule, employeeId: string): boolean {
  return rule.source !== 'manual' || rule.subjectEmployeeId === employeeId;
}

function considered(
  rule: Rule,
  matched: boolean,
  trace: TraceNode,
  status: ConsideredRule['status'],
  reason: string,
): ConsideredRule {
  return { ruleId: rule.ruleId, ruleName: rule.name, matched, status, reason, trace };
}

/**
 * A manual override wins on `source`, not on `priority` (D9). Describing a
 * priority-0 override as the "highest priority" rule makes the explanation
 * contradict the comparator, which is exactly the confusion an HR admin
 * reading this panel cannot afford.
 */
function describeHead(rule: Rule, effect: Effect): { status: ConsideredRule['status']; reason: string } {
  const manual = rule.source === 'manual';
  if (effect === 'grant') {
    return {
      status: 'applied',
      reason: manual
        ? `applied as a manual override for this employee: ${rule.name}`
        : `applied as highest priority matching rule: ${rule.name}`,
    };
  }
  return {
    status: 'denied',
    reason: manual ? `denied by a manual override for this employee: ${rule.name}` : `denied by ${rule.name}`,
  };
}

function describeShadow(head: Rule): string {
  return head.source === 'manual'
    ? `shadowed by a manual override for this employee: ${head.name}`
    : `shadowed by ${head.name}`;
}

export function resolveSlot(slot: Slot, rules: Rule[], state: EmployeeState, asOf: Date): SlotResolution {
  const candidates: Candidate[] = rules
    .filter((r) => r.slotId === slot.id && appliesToEmployee(r, state.employee_id))
    .map((r) => ({ rule: r, ...evaluate(r.criteria, state, asOf) }))
    .sort((a, b) => compareRules(a.rule, b.rule));

  const resolved: { targetId: string; winningRuleId: string; winningRuleVersionId: string }[] = [];
  const consideredOut: ConsideredRule[] = [];
  let unassignedWarning = false;

  if (slot.cardinality === 'exactly_one' || slot.cardinality === 'at_most_one') {
    const headIndex = candidates.findIndex((c) => c.matched);

    if (headIndex === -1) {
      unassignedWarning = slot.cardinality === 'exactly_one';
      for (const c of candidates) {
        consideredOut.push(considered(c.rule, false, c.trace, 'not_matched', c.trace.detail));
      }
    } else {
      const head = candidates[headIndex];
      const headDesc = describeHead(head.rule, head.rule.effect);
      for (let i = 0; i < candidates.length; i++) {
        const c = candidates[i];
        if (!c.matched) {
          consideredOut.push(considered(c.rule, false, c.trace, 'not_matched', c.trace.detail));
          continue;
        }
        if (i === headIndex) {
          if (head.rule.effect === 'grant') {
            resolved.push({ targetId: head.rule.targetId, winningRuleId: head.rule.ruleId, winningRuleVersionId: head.rule.id });
          }
          consideredOut.push(
            considered(head.rule, true, head.trace, headDesc.status, headDesc.reason),
          );
        } else {
          consideredOut.push(considered(c.rule, true, c.trace, 'shadowed', describeShadow(head.rule)));
        }
      }
    }
  } else {
    // many: group matched rules by targetId, highest-ranked rule per group wins.
    const groupHeadByTarget = new Map<string, Candidate>();
    for (const c of candidates) {
      if (!c.matched) {
        consideredOut.push(considered(c.rule, false, c.trace, 'not_matched', c.trace.detail));
        continue;
      }
      const existing = groupHeadByTarget.get(c.rule.targetId);
      if (!existing) {
        groupHeadByTarget.set(c.rule.targetId, c);
        const headDesc = describeHead(c.rule, c.rule.effect);
        if (c.rule.effect === 'grant') {
          resolved.push({ targetId: c.rule.targetId, winningRuleId: c.rule.ruleId, winningRuleVersionId: c.rule.id });
        }
        consideredOut.push(considered(c.rule, true, c.trace, headDesc.status, headDesc.reason));
      } else {
        consideredOut.push(
          considered(c.rule, true, c.trace, 'shadowed', describeShadow(existing.rule)),
        );
      }
    }
  }

  return {
    slotKey: slot.key,
    cardinality: slot.cardinality,
    resolved,
    unassignedWarning,
    considered: consideredOut,
  };
}

export function resolveEmployee(slots: Slot[], rules: Rule[], state: EmployeeState, asOf: Date): EmployeeResolution {
  const slotResolutions = slots.map((slot) => resolveSlot(slot, rules, state, asOf));
  const slotByKey = new Map(slots.map((s) => [s.key, s]));

  const assignments: ResolvedAssignment[] = [];
  for (const sr of slotResolutions) {
    const slot = slotByKey.get(sr.slotKey);
    if (!slot) continue;
    for (const r of sr.resolved) {
      assignments.push({
        employeeId: state.employee_id,
        slotId: slot.id,
        targetId: r.targetId,
        winningRuleId: r.winningRuleId,
        winningRuleVersionId: r.winningRuleVersionId,
        validFrom: asOf,
        validTo: null,
      });
    }
  }

  return { employeeId: state.employee_id, asOf, slots: slotResolutions, assignments };
}
